-----------------------------------------UPDATED_AT TRIGGER-----------------------------------------

CREATE TRIGGER FINTECH.SPECIAL_EXTRA_CHARGE_RATE_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.SPECIAL_EXTRA_CHARGE_RATE
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.PRIVATELY_OWNED_GROUP_SCORE_MAXIMUM_EXTRA_CHARGE_RATE_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.PRIVATELY_OWNED_GROUP_SCORE_MAXIMUM_EXTRA_CHARGE_RATE_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.CORPORATION_OWNED_GROUP_SCORE_MAXIMUM_EXTRA_CHARGE_RATE_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.CORPORATION_OWNED_GROUP_SCORE_MAXIMUM_EXTRA_CHARGE_RATE_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.INSURED_CHARACTERISTICS_RATE_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.INSURED_CHARACTERISTICS_RATE
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.SUBSCRIPTION_EXPERIENCE_RATE_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.SUBSCRIPTION_EXPERIENCE_RATE_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.SUBSCRIPTION_EXPERIENCE_RATE_VARIABLE_DATA_VALUE_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.SUBSCRIPTION_EXPERIENCE_RATE_VARIABLE_DATA_VALUE
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.INDIVIDUAL_DISCOUNT_EXTRA_CHARGE_RATE_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.INDIVIDUAL_DISCOUNT_EXTRA_CHARGE_RATE
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.NEW_ACCIDENT_SCORE_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.NEW_ACCIDENT_SCORE_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.FOLLOW_UP_ACTION_SCORE_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.FOLLOW_UP_ACTION_SCORE_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.ACCIDENT_CAUSE_SCORE_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.ACCIDENT_CAUSE_SCORE_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.DEFAULT_AND_NEW_CONTRACT_APPLIED_GRADE_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.DEFAULT_AND_NEW_CONTRACT_APPLIED_GRADE_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.RENEWAL_CONTRACT_EVALUATION_STANDARD_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.RENEWAL_CONTRACT_EVALUATION_STANDARD_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.RENEWAL_CONTRACT_APPLIED_RATE_EXP_PERIOD_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.RENEWAL_CONTRACT_APPLIED_RATE_EXP_PERIOD_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.EVALUATION_PERIOD_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.EVALUATION_PERIOD_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.RANGE_RATE_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.RANGE_RATE_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.RANGE_RATE_VARIABLE_DATA_VALUE_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.RANGE_RATE_VARIABLE_DATA_VALUE
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.INHERITED_INSURANCE_GRADE_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.INHERITED_INSURANCE_GRADE_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.INHERITED_INSURANCE_GRADE_VARIABLE_DATA_VALUE_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.INHERITED_INSURANCE_GRADE_VARIABLE_DATA_VALUE
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.APPLIED_RATE_BY_DEFAULT_AND_APPLIED_GRADE_VARIABLE_DATA_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.APPLIED_RATE_BY_DEFAULT_AND_APPLIED_GRADE_VARIABLE_DATA
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;

CREATE TRIGGER FINTECH.APPLIED_RATE_BY_DEFAULT_AND_APPLIED_GRADE_VARIABLE_DATA_VALUE_UPDATED_AT_TRIGGER
BEFORE UPDATE ON FINTECH.APPLIED_RATE_BY_DEFAULT_AND_APPLIED_GRADE_VARIABLE_DATA_VALUE
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul';
END;
